clone_depth: 10

clone_folder: c:\projects\scs

environment:
  global:
    # Taken from scipy appveyor.yml.
    MINGW_32: C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin
    MINGW_64: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin
    OPENBLAS_32: https://3f23b170c54c2533c070-1c8a9b3114517dc5fe17b7c3f8c63a43.ssl.cf2.rackcdn.com/openblas-5f998ef_gcc7_1_0_win32.zip
    OPENBLAS_64: https://3f23b170c54c2533c070-1c8a9b3114517dc5fe17b7c3f8c63a43.ssl.cf2.rackcdn.com/openblas-5f998ef_gcc7_1_0_win64.zip


platform:
  #- x86
  - x64

install:
  - ps: (new-object System.Net.WebClient).DownloadFile($env:OPENBLAS_64, 'c:\openblas.zip')
  - ps: Expand-Archive c:\openblas.zip c:\projects
  - ps: Get-ChileItem -Path C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin\

build_script:
  - dir C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin\
  - cd c:\projects\scs
  - C:\MinGW\bin\mingw32-make.exe CC=C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin\mingw-w64-x86_64-gcc BLASLDFLAGS="C:/"
