clone_depth: 10

clone_folder: c:\projects\scs

environment:
  global:
      # Taken from scipy appveyor.yml.
    - OPENBLAS: https://3f23b170c54c2533c070-1c8a9b3114517dc5fe17b7c3f8c63a43.ssl.cf2.rackcdn.com/openblas-5f998ef_gcc7_1_0_win
  matrix:
    - platform: x64
      ARCH: 64

    - platform: x86
      ARCH: 32

build_script:
  - ps: $file = $env:OPENBLAS + $env:ARCH + ".zip"
  - ps: (new-object System.Net.WebClient).DownloadFile($file, 'c:\openblas.zip')
  - ps: Expand-Archive c:\openblas.zip c:\projects\openblas
  - set PATH=%PATH%;C:\msys%ARCH%\mingw%ARCH%\bin;C:\projects\openblas\%ARCH%\bin
  - dir C:\msys%ARCH%\mingw%ARCH%\bin
  - echo %path%
  - cd C:\projects\scs
  - mingw32-make.exe CC="gcc.exe -m%ARCH%" USE_LAPACK=1 BLASLDFLAGS="-LC:\projects\openblas\%ARCH%\bin -lopenblas_5f998ef_gcc7_1_0"
  - mingw32-make.exe test CC="gcc.exe -m%ARCH%" USE_LAPACK=1 BLASLDFLAGS="-LC:\projects\openblas\%ARCH%\bin -lopenblas_5f998ef_gcc7_1_0"

test_script:
  - C:\projects\scs\out\run_tests.exe
