matrix:
  include:
    - os: linux
      compiler: clang
      env: CFLAGS="-fsanitize=memory -fno-omit-frame-pointer"
    - os: linux
      compiler: clang
      env: CFLAGS="-fsanitize=address -fno-omit-frame-pointer"
    - os: linux
      compiler: clang
      env: CFLAGS="-fsanitize=undefined -fno-omit-frame-pointer"
    - os: linux
      compiler: clang
      env: CFLAGS="-fsanitize=thread -fno-omit-frame-pointer"
    - os: linux
      compiler: gcc
    - os: osx

language: C

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get install liblapack-dev;
    fi

script:
  # Use -O1 for santizers to work.
  - make OPT=-O1
  - make test OPT=-O1
  - test/run_tests

notifications:
  email:
    - bodonoghue85@gmail.com

