matrix:
  include:
    - os: linux
      env: CC="clang -fsanitize=memory -fno-omit-frame-pointer" OPT="-O1"
    - os: linux
      env: CC="clang -fsanitize=address -fno-omit-frame-pointer" OPT="-O1"
    - os: linux
    - os: osx

language: C

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get install liblapack-dev;
    fi

script:
  - make
  - make test
  - out/run_tests

notifications:
  email:
    - bodonoghue85@gmail.com

