os:
  - linux
  - osx
language: C
compiler:
  - gcc
  - clang
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get install liblapack-dev;
    fi
script:
  - make CC="clang -fsanitize=memory -fno-omit-frame-pointer"
  - make CC="clang -fsanitize=memory -fno-omit-frame-pointer" test
  - out/run_tests 
  - make purge
  - make CC="clang -fsanitize=address -fno-omit-frame-pointer"
  - make CC="clang -fsanitize=address -fno-omit-frame-pointer" test
  - out/run_tests 
notifications:
  email:
    - bodonoghue85@gmail.com

